import { LegalPage } from "@/components/legal/legal-page";

export const metadata = {
  title: "Terms of Service - Lightning AI Solutions",
  description: "Read our terms and conditions for using Lightning AI Solutions services.",
};

const sections = [
  {
    title: "1. Acceptance of Terms",
    content: `By accessing or using the services of Lightning AI Solutions ("Company", "we", "us", or "our"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, do not use our services.`,
  },
  {
    title: "2. Services Description",
    content: `Lightning AI Solutions provides AI product development, LLM fine-tuning, voice AI agents, intelligent automation, and AI analytics services. We reserve the right to modify, suspend, or discontinue any part of our services at any time.`,
  },
  {
    title: "3. User Responsibilities",
    content: `You agree to:

- Provide accurate and complete information
- Maintain the security of your account credentials
- Use our services in compliance with applicable laws
- Not engage in any activity that interferes with our services
- Not use our services for illegal, harmful, or fraudulent purposes
- Respect intellectual property rights`,
  },
  {
    title: "4. Service Agreements",
    content: `Specific project engagements will be governed by separate service agreements or statements of work. These Terms supplement, but do not replace, such agreements.`,
  },
  {
    title: "5. Intellectual Property",
    content: `**Our IP:** All content, features, and functionality of our services remain the exclusive property of Lightning AI Solutions.

**Client IP:** You retain ownership of any data, content, or materials you provide to us.

**Deliverables:** Unless otherwise specified in a service agreement, you will own the final deliverables created specifically for you. We retain the right to use general methodologies, techniques, and know-how developed during the project.

**Portfolio Rights:** We reserve the right to showcase our work (with your permission) in our portfolio and marketing materials.`,
  },
  {
    title: "6. Payment Terms",
    content: `**Project Fees:** Payment terms will be specified in individual service agreements.

**Invoicing:** Invoices are typically sent at project milestones or monthly for retainer agreements.

**Payment Due:** Payment is due within 15 days of invoice date unless otherwise agreed.

**Late Payment:** Late payments may incur interest charges and may result in service suspension.

**Refunds:** Refund policies are outlined in our Refund Policy.`,
  },
  {
    title: "7. Confidentiality",
    content: `We will maintain the confidentiality of any proprietary or confidential information you share with us. We may enter into separate Non-Disclosure Agreements (NDAs) for sensitive projects.`,
  },
  {
    title: "8. Warranties and Disclaimers",
    content: `**Our Commitment:** We will perform services in a professional and workmanlike manner.

**Disclaimer:** Services are provided "as is" without warranties of any kind, either express or implied. We do not guarantee specific results or outcomes.

**AI Limitations:** AI systems may produce unpredictable results. We are not liable for outputs generated by AI models.`,
  },
  {
    title: "9. Limitation of Liability",
    content: `To the maximum extent permitted by law, Lightning AI Solutions shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues.

Our total liability shall not exceed the amount paid by you for the services in the 12 months preceding the claim.`,
  },
  {
    title: "10. Indemnification",
    content: `You agree to indemnify and hold harmless Lightning AI Solutions from any claims, damages, or expenses arising from your use of our services or violation of these Terms.`,
  },
  {
    title: "11. Term and Termination",
    content: `**Term:** These Terms remain in effect while you use our services.

**Termination:** Either party may terminate a service agreement according to its terms. We may suspend or terminate access for violation of these Terms.

**Effect of Termination:** Upon termination, you must cease using our services. Provisions that should survive termination (e.g., confidentiality, IP rights) will continue.`,
  },
  {
    title: "12. Dispute Resolution",
    content: `**Governing Law:** These Terms are governed by the laws of India.

**Negotiation:** Parties will attempt to resolve disputes through good faith negotiation.

**Arbitration:** If negotiation fails, disputes will be resolved through binding arbitration in Anand, Gujarat, India.`,
  },
  {
    title: "13. Changes to Terms",
    content: `We may modify these Terms at any time. We will notify you of significant changes. Continued use of our services after changes constitutes acceptance of the new Terms.`,
  },
  {
    title: "14. Contact Information",
    content: `For questions about these Terms, contact us:

**Lightning AI Solutions**
Email: umang@lightningaisolutions.in
Phone: +91 9426154668
Address: 6/A Chinar Gulnar, Anand Vidhyanagar Road, Anand, Gujarat, India - 388001`,
  },
];

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms of Service"
      lastUpdated="October 26, 2025"
      sections={sections}
    />
  );
}
